### ISSUE TITLE
Index won't load

### ISSUE THREAD

**Issue by m-akinc** [KirillOsenkov/SourceBrowser#147]
Whenever a search is entered, the pane shows:

```
Index is being rebuilt... 0%
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
 at Microsoft.SourceBrowser.SourceIndexServer.Models.IndexLoader.FillProjectToAssemblyMap(List`1 assemblies, List`1 projects, Dictionary`2 projectToAssemblyMap) in C:\SourceBrowser\src\SourceIndexServer\Models\IndexLoader.cs:line 186
 at Microsoft.SourceBrowser.SourceIndexServer.Models.IndexLoader.ReadFilesCore(Index index, String rootPath) in C:\SourceBrowser\src\SourceIndexServer\Models\IndexLoader.cs:line 73
 at Microsoft.SourceBrowser.SourceIndexServer.Models.IndexLoader.ReadIndex(Index index, String rootPath) in C:\SourceBrowser\src\SourceIndexServer\Models\IndexLoader.cs:line 22

```
My guess is that `Serialization.ReadProjects` is returning an empty array due to this logic:
```
           if (!File.Exists(folderPath))
            {
                return Array.Empty<string>();
            }
```
The folder path is not a file, so exists should return false.

**Comment by KirillOsenkov** [comment]
Published the fix in 1.0.31.
