### ISSUE TITLE
Could not load file or assembly 'System.Threading.Tasks.Dataflow' when running from build server.

### ISSUE THREAD

**Issue by kobi** [KirillOsenkov/SourceBrowser#21]
I've wrote a small script that download SourceBrowser from NuGet and runs it daily on our build server - a Windows 7 server with .Net 4.6 installed (Windows 2008 R2 didn't work either).
I get this exception while it runs:

```
09:49:48 Failed to open solution: D:\Jenkins\Slave\job\solution.sln
System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Build.BackEnd.Logging.LoggingService.ProcessLoggingEvent(Object buildEvent, Boolean allowThrottling)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LogInvalidProjectFileError(BuildEventContext buildEventContext, InvalidProjectFileException invalidProjectFileException)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFileLoader.<LoadProjectAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFileLoader.<LoadProjectFileAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<LoadProjectAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<GetOrLoadProjectAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenSolutionAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.SourceBrowser.HtmlGenerator.SolutionGenerator.CreateSolution(String solutionFilePath, ImmutableDictionary`2 properties)
```
I solved this issue in another server by installing Visual Studio 2015 - is this required?

**Comment by drose-d2l** [comment]
You may need [MSBuildTools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159)

**Comment by KirillOsenkov** [comment]
Make sure you can build your solution on that server:
    MSBuild /m D:\Jenkins\Slave\job\solution.sln

It is likely that you need to restore nuget packages for your solution:
    nuget restore D:\Jenkins\Slave\job\solution.sln

Remember that SourceBrowser only works on a solution if you can build it with MSBuild.

**Comment by KirillOsenkov** [comment]
I don't think Visual Studio 2015 is required to run Source Browser, but it might be required to build your solution.

**Comment by kobi** [comment]
That's exactly my issue - I *can* build my project with MSBuild (though I'm using an older version). This is our build server, and the solution compiles without any problem. It doesn't require Visual Studio on the server, and it uses NuGet package restore (I also tried to restore the packages manually, it didn't help). It's a VS 2012 solution, by the way.

I'll try using another solution to make sure, and try installing MSBuildTools 2015 as @drose-d2l suggested.

**Comment by KirillOsenkov** [comment]
A few things:
1. run gacutil /l system.threading.tasks.dataflow, what does it display? Is System.Threading.Tasks.Dataflow.dll in the GAC on the build server?
2. Does your solution require System.Threading.Tasks.Dataflow.dll?
3. I think @drose-d2l is right, MSBuild tools 2015 are needed for SourceBrowser to work

**Comment by kobi** [comment]
`gacutil` gives this output:

```
The Global Assembly Cache contains the following assemblies:
  system.threading.tasks.dataflow, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL

Number of items = 1
```

My solution does not require System.Threading.Tasks.Dataflow.dll. I also tried with another solution (VS 2015 solution, with just one project and a few files), and I'm getting the same error.

After installing [Microsoft Build Tools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159), `gacutil` looks better:
```
The Global Assembly Cache contains the following assemblies:
  system.threading.tasks.dataflow, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL
  system.threading.tasks.dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL

Number of items = 2
```
Now SourceBrowser can index the small solution, so the problem is solved. My solution has a new error, missing `.targes` file, but that is something I can solve (probably a wrong `Condition` in my .csproj). Thanks!
