### ISSUE TITLE
source.dot.net is out of date

### ISSUE THREAD

**Issue by svick** [KirillOsenkov/SourceBrowser#96]
When I go to [source.dot.net](https://source.dot.net) and find [the System.Private.CoreLib assembly](https://source.dot.net/#System.Private.CoreLib/), it says "Indexed on: March 15". This means the code there is more than a month old. I think it should be updated.

**Comment by KirillOsenkov** [comment]
@alexperovich is there anything I can help with perhaps? Have you talked to anybody about making the site more official or more funded? I know that running these sites as a volunteer is hard :|

Also cc @natemcmaster just in case.

**Comment by alexperovich** [comment]
Okay, now with the latest build its getting the following error
```
2018-05-30T10:27:02.6438965Z   10:27:02 Reading assembly names from F:\a\_work\6\s\bin\repo\corefxlab\src\System.Azure.Experimental\System.Azure.Experimental.csproj
2018-05-30T10:27:03.0129542Z   Unhandled Exception: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Missing resource ''
2018-05-30T10:27:03.0132537Z      at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
2018-05-30T10:27:03.0135605Z      at Microsoft.Build.Shared.ErrorUtilities.VerifyThrow(Boolean condition, String unformattedMessage, Object arg0)
2018-05-30T10:27:03.0136320Z      at Microsoft.Build.Shared.AssemblyResources.GetStringFromEngineResources(String name)
2018-05-30T10:27:03.0136905Z      at Microsoft.Build.Shared.AssemblyResources.GetString(String name)
2018-05-30T10:27:03.0139346Z      at Microsoft.Build.BackEnd.Logging.LoggingService.LogWarningFromText(BuildEventContext buildEventContext, String subcategoryResourceName, String warningCode, String helpKeyword, BuildEventFileInfo file, String message)
2018-05-30T10:27:03.0146279Z      at Microsoft.Build.BackEnd.Logging.LoggingService.LogWarning(BuildEventContext buildEventContext, String subcategoryResourceName, BuildEventFileInfo file, String messageResourceName, Object[] messageArgs)
2018-05-30T10:27:03.0150850Z      at Microsoft.Build.BackEnd.Logging.LoggingContext.LogWarning(String subcategoryResourceName, BuildEventFileInfo file, String messageResourceName, Object[] messageArgs)
2018-05-30T10:27:03.0152147Z      at Microsoft.Build.BackEnd.SdkResolverLoader.LoadResolvers(LoggingContext loggingContext, ElementLocation location)
2018-05-30T10:27:03.0153098Z      at Microsoft.Build.BackEnd.SdkResolution.Initialize(LoggingContext loggingContext, ElementLocation location)
2018-05-30T10:27:03.0153939Z      at Microsoft.Build.BackEnd.SdkResolution.GetSdkPath(SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath)
2018-05-30T10:27:03.0163198Z      at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError)
2018-05-30T10:27:03.0165204Z      at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
2018-05-30T10:27:03.0166169Z      at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
2018-05-30T10:27:03.0167340Z      at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
2018-05-30T10:27:03.0167719Z      at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
2018-05-30T10:27:03.0168235Z      at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
2018-05-30T10:27:03.0168617Z      at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
2018-05-30T10:27:03.0169001Z      at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
2018-05-30T10:27:03.0169454Z      at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
2018-05-30T10:27:03.0170231Z      at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
2018-05-30T10:27:03.0170653Z      at Microsoft.SourceBrowser.Common.AssemblyNameExtractor.GetAssemblyNameFromProject(String projectFilePath) in F:\a\_work\6\s\src\SourceBrowser\src\Common\AssemblyNameExtractor.cs:line 75
2018-05-30T10:27:03.0171335Z      at Microsoft.SourceBrowser.Common.AssemblyNameExtractor.GetAssemblyNames(String projectOrSolutionFilePath) in F:\a\_work\6\s\src\SourceBrowser\src\Common\AssemblyNameExtractor.cs:line 31
2018-05-30T10:27:03.0171896Z      at Microsoft.SourceBrowser.HtmlGenerator.Program.IndexSolutions(IEnumerable`1 solutionFilePaths, Dictionary`2 properties, Federation federation, Dictionary`2 serverPathMappings, IEnumerable`1 pluginBlacklist) in F:\a\_work\6\s\src\SourceBrowser\src\HtmlGenerator\Program.cs:line 279
2018-05-30T10:27:03.0172595Z      at Microsoft.SourceBrowser.HtmlGenerator.Program.Main(String[] args) in F:\a\_work\6\s\src\SourceBrowser\src\HtmlGenerator\Program.cs:line 198
```
Unfortunately I don't have any cycles right now to debug this.

**Comment by KirillOsenkov** [comment]
@alexperovich this rings a bell: https://github.com/Microsoft/msbuild/issues/2997

I think the solution would be to update MSBuild NuGet packages to latest in your fork. I've done that in https://github.com/KirillOsenkov/SourceBrowser master branch.

**Comment by alexperovich** [comment]
Okay, dotnet/source-indexer#11 should fix this.

**Comment by stephentoub** [comment]
> Okay, dotnet/source-indexer#11 should fix this.

Yay, it'll be great to have source.dot.net up-to-date again.

**Comment by alexperovich** [comment]
Fix merged. source.dot.net should be updated in the morning after the build finishes.

**Comment by alexperovich** [comment]
Alright, https://source.dot.net/ has been successfully updated.

**Comment by stephentoub** [comment]
Thanks, Alex. And it should now stay up to date, updating daily?

**Comment by alexperovich** [comment]
Yep, ill keep an eye on the build and fix it again if it breaks.

**Comment by KirillOsenkov** [comment]
Wonderful, thanks a lot! Closing this issue for now.
